[build]
  command = "ng build --configuration production"
  publish = "dist/<your-project-name>"

[functions]
  node_bundler = "esbuild"

[plugins]
  package = "@netlify/plugin-angular" # Not @netlify/angular-runtime
